### ISSUE TITLE
Lack of data for equipments

### ISSUE THREAD

**Issue by ferrerojosh** [ferrerojosh/angryraids#2]
Formulas if possible, or static data if applicable really need community help on this one

**Comment by ferrerojosh** [comment]
Stars
```Type    0*    1*    2*    3*    4*    5*
UW    1    1.1    1.3    1.6    2    2.5
Armor    1    1.1    1.25    1.45    1.7    2
everything else    1    1.1    1.2    1.3    1.4    1.5
```

**Comment by ferrerojosh** [comment]
>  I thought I remembered base value of gear starting at +1, and +0 is 0.9, +2 is 1.1, +3 is 1.2, etc. But it looks like I'm off a bit.
it still starts at +1, but the difference is like 0.09909

**Comment by duckness** [comment]
actually I was wrong, it starts at level 0, then every level increases the base by 11%.

so:

level | value
---|---
0 | 1
1 | 1.11
2 |  1.22
3 |  1.33
4 | 1.44

etc

**Comment by ferrerojosh** [comment]
Yep, I was experimenting as well, wrote the code just now

```JavaScript
let base = 1993
for(let i = 0; i <= 20; i++) {
	let coeff = 1 + (i * 0.11)
	let result = Math.floor(base * coeff)
	console.log(result)
}
```

This issue is resolved I guess ?
