### ISSUE TITLE
Rune and item options data

### ISSUE THREAD

**Issue by ferrerojosh** [ferrerojosh/angryraids#5]
Lacking much data, would require time

**Comment by duckness** [comment]
## Runes
### Weapon 

Rune | Type | Heroic | Ancient
---|---|---|---
Rune of Fierce Attack | Atk | 15% | 20%
Rune of Sharpness | Penetration | 150 | 200
Rune of Iron Wall | P.Block DEF | 150 | 200
Rune of Toughness | P.Tough | 150 | 200
Rune of Denial | M.Block DEF | 150 | 200
Rune of Willpower | M.Tough | 150 | 200
Rune of Thirst | Lifesteal | 150 | 200
Rune of Agitation | MP/Atk | 50% | 60%

### Main Armor

Rune | Type | Heroic | Ancient
---|---|---|---
Rune of Frenzy | Crit DMG | 30% | 40%
Rune of Precision | ACC | 150 | 200
Rune of Steel | P.Block | 150 | 200
Rune of Patience | P.DEF | 30% | 40%
Rune of Exclusion | M.Block | 150 | 200
Rune of Protection | M.DEF | 30% | 40%
Rune of Resistance | CC Resist | 150 | 200
Rune of Stamina | Max HP | 15% | 20%

### Secondary Armor

Rune | Type | Heroic | Ancient
---|---|---|---
Rune of the Heartless | Crit | 150 | 200
Rune of Agility | P.Dodge | 150 | 200
Rune of Flexibility | M.Dodge | 150 | 200
Rune of Potential | MP/DMG | 50% | 60%

**Comment by duckness** [comment]
## Options

Type | Min | Max | Increments
---|---|---|---
Atk | 6% | 11% | 0.5%
Atk Spd | 60 | 110 | 5
Crit | 60 | 110 | 5
Crit DMG | 12% | 22% | 1%
Penetration | 60 | 110 | 5
ACC | 60 | 110 | 5
Lifesteal | 60 | 110 | 5
Max HP | 6% | 11% | 0.5%
M.DEF |  6% | 11% | 0.5%
P.DEF |  6% | 11% | 0.5%
P.Block | 120 | 220 | 10
P.Dodge | 60 | 110 | 5
CC Resist | 60 | 110 | 5

**Comment by ferrerojosh** [comment]
Thanks for data, will add this the moment I have time
